### ISSUE TITLE
SSL Error. Failed to validate the certificate chain.

### ISSUE THREAD

**Issue by Gerst20051** [oauth-io/oauth-android#2]
`TAG: X509Util - Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Any ideas?

**Comment by vinaychenna** [comment]
Thanks :) This worked for me too.

**Comment by allthetime** [comment]
I know this is closed, but for posterity... this answer is not a good idea. It basically disables SSL and makes it almost pointless to be using it. This error points to an issue with your server SSL configuration, normally the lack of an _intermediate certificate_ which helps the browser (webView, etc.) verify a certificate chain, from your personal certificate, to the certificate authorities that your browser will recognize as valid. 

Here is a short article that describes the issue: http://steveliles.github.io/android_ssl_certificate_not_trusted.html

In terms of solving it, that will be up to you and what server/cert you are using. For instance, this is what we had to do, using nginx and startssl: 

http://www.westphahl.net/blog/2012/01/03/setting-up-https-with-nginx-and-startssl/

**Comment by Gerst20051** [comment]
yeah i think it's obvious that you wouldn't wanna use this solution in a production environment but it's perfectly fine to disable ssl on a development environment.

**Comment by allthetime** [comment]
Oh yeah, fair enough! Just wanted to make sure no one used this in production thinking they were still secure!

**Comment by tomercagan** [comment]
@allthetime though related to other project (working on a corodva app) your comment really helped me understand what is going on and why my application no connecting after I made a release version ([see here](http://stackoverflow.com/a/36135281/904521)). And thanks @Gerst20051 for opening this issue ;)

**Comment by RyanNewsom** [comment]
A better solution that won't get you man in the middled.
I was dealing with this and quite frankly allowing MITM attacks is a no-no. Here is a cleaner solution that supports pinning. Save the certificate into your raw resource folder.    
NOTE: Sadly, SSLError gives us an SslCertificate when you call getCertificate(). SslCertificate is kind of useless. It's public API doesn't allow you to verify the public key, only the created on, expired date, issued to, issued by. However, if you open up this class you will see an X509Certificate member variable that is un-exposed. IDK why this design decision was taken. But there is an API for getting the Bundle, and that X509 Certificate member variable gets stored in there. So we access it that way, because the Certificate has a lot more useful methods on it.

    @Override
    public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
        SslCertificate sslCertificateServer = error.getCertificate();
        Certificate pinnedCert = getCertificateForRawResource(R.raw.your_cert, mContext);
        Certificate serverCert = convertSSLCertificateToCertificate(sslCertificateServer);
        
        if(pinnedCert.equals(serverCert)) {
            handler.proceed();
        } else {
            super.onReceivedSslError(view, handler, error);
        }
    }

    public static Certificate getCertificateForRawResource(int resourceId, Context context) {
        CertificateFactory cf = null;
        Certificate ca = null;
        Resources resources = context.getResources();
        InputStream caInput = resources.openRawResource(resourceId);

        try {
            cf = CertificateFactory.getInstance("X.509");
            ca = cf.generateCertificate(caInput);
        } catch (CertificateException e) {
            Log.e(TAG, "exception", e);
        } finally {
            try {
                caInput.close();
            } catch (IOException e) {
                Log.e(TAG, "exception", e);
            }
        }

        return ca;
    }

    public static Certificate convertSSLCertificateToCertificate(SslCertificate sslCertificate) {
        CertificateFactory cf = null;
        Certificate certificate = null;
        Bundle bundle = sslCertificate.saveState(sslCertificate);
        byte[] bytes = bundle.getByteArray("x509-certificate");

        if (bytes != null) {
            try {
                CertificateFactory certFactory = CertificateFactory.getInstance("X.509");
                Certificate cert = certFactory.generateCertificate(new ByteArrayInputStream(bytes));
                certificate = cert;
            } catch (CertificateException e) {
                Log.e(TAG, "exception", e);
            }
        }

        return certificate;
    }
