### ISSUE TITLE
fitbit login page is not responsive in Android devices

### ISSUE THREAD

**Issue by IndoNinja** [oauth-io/oauth-android#5]
when calling fitbit login page is not responsive, password field is hiding by keyboard in ANdroid, but coming properly in IOS. Android fitbit login page is different then fitbit login page in IOS. 
you can see difference in attached images,For IOS image name:IOS_fitbit_login and Android image: android_fitbit_login
![android_fitbit_login](https://cloud.githubusercontent.com/assets/5971214/8377042/42a35e24-1c2b-11e5-9e0a-db8a41ea8cee.png)
![ios_fitbit_login](https://cloud.githubusercontent.com/assets/5971214/8377043/42a4c3b8-1c2b-11e5-96c1-2f17345a079f.png)

**Comment by thyb** [comment]
Fitbit has a param for mobile view

”We also have a second version of the OAuth UI tailored for mobile browsers. The optional display parameter, when specified, indicates that we should display the dialog optimized for mobile browsers; when it is omitted we display the dialog optimized for desktop browsers.
REDIRECT to https://www.fitbit.com/oauth/authorize?oauth_token=<temporary-token>[&locale=<locale>][&display=touch][&requestCredentials=true]”

With the iOS and Phonegap SDK, it automatically load the mobile view as it is described in our configuration files:
https://github.com/oauth-io/oauthd/blob/master/providers/fitbit/conf.json#L7

Android doesn’t have this feature yet, but you can specify the option manually:

```
JSONObject opts = new JSONObject(); 
JSONObject authorize_opts = new JSONObject(); 
authorize_opts.put("display", "touch"); 
opts.put("authorize", authorize_opts); 
oauth.popup("fitbit", opts, callback);
```
